booksthismonth/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

urlpatterns = [
	path('books/<search>', get_books, name='books'),
	path('', view_booksthismonth, name='booksthismonth'),
]

feedbackpage/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

urlpatterns = [
	path('', view_feedbackpage, name='feedbackpage'),
]

loginpage/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

urlpatterns = [
	path('', view_loginpage, name='loginpage'),
]

profilepage/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

urlpatterns = [
	path('logout', logout_view, name='logout'),
	path('', view_profilepage, name='profilepage'),
]

registrationpage/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

urlpatterns = [
	path('create', create_subscriber, name='create_subscriber'),
	path('subscribers', get_subscribers, name='get_subscribers'),
	path('', view_registrationpage, name='registrationpage'),
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('booksthismonth.urls')),
    path('profile/', include('profilepage.urls')),
    path('feedback/', include('feedbackpage.urls')),
    path('login/', include(('loginpage.urls', 'loginpage'), namespace='login')),
    path('subscribe/', include('registrationpage.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('', include(('profilepage.urls', 'profilepage'), namespace='home')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

booksthismonth/models.py
from django.db import models

# Create your models here.

feedbackpage/models.py
from django.db import models

# Create your models here.

class Guest(models.Model):
	name = models.CharField(max_length=100, blank=True)
	email = models.CharField(max_length=100, blank=True)
	phone_number = models.CharField(max_length=100, blank=True)
	feedback = models.TextField()

loginpage/models.py
from django.db import models

# Create your models here.

profilepage/models.py
from django.db import models

# Create your models here.

registrationpage/models.py
from django.db import models

# Create your models here.

class Subscriber(models.Model):
	name = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	password = models.CharField(max_length=100)

feedbackpage/forms.py
from django import forms
from .models import Guest

class Feedback_Form(forms.ModelForm):
	name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
	phone_number = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
	feedback = forms.CharField(required=True, widget=forms.Textarea(attrs={'class':'form-control'}))

	class Meta:
		model = Guest
		fields = ['name', 'email', 'phone_number', 'feedback']

registrationpage/forms.py
from django import forms
from .models import Subscriber

class Subscribe_Form(forms.ModelForm):
	name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
	password = forms.CharField(max_length=32, widget=forms.PasswordInput())

	class Meta:
		model = Subscriber
		fields = ['name', 'email', 'password']

booksthismonth/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests

# Create your views here.

def get_books(request, search):
	url = 'https://www.googleapis.com/books/v1/volumes?q=' + search
	books = json.loads(requests.get(url).text)
	return JsonResponse(books)

def view_booksthismonth(request):
	return render(request, 'Booksthismonth.html')

feedbackpage/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from .forms import Feedback_Form
from .models import Guest

# Create your views here.

def view_feedbackpage(request):
	form = Feedback_Form()
	if request.method == 'POST':
		form = Feedback_Form(request.POST)
		if form.is_valid():
			new_feedback = form.save()
			return HttpResponseRedirect(reverse('profilepage'))
		else:
			form = Feedback_Form()
	return render(request, 'Feedbackpage.html', {'form':form})

loginpage/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect

# Create your views here.

def view_loginpage(request):
	return render(request, 'Loginpage.html')

profilepage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
from django.urls import reverse

# Create your views here.

def view_profilepage(request):
	return render(request, 'Profilepage.html')

def logout_view(request):
	logout(request)
	request.session.flush()
	return HttpResponseRedirect(reverse("home:profilepage"))

registrationpage/views.py
from django.shortcuts import render, reverse
from django.core import serializers
from django.http import HttpResponse
from django.http import JsonResponse
from .forms import Subscribe_Form
from .models import Subscriber
import json
import requests

# Create your views here.

def make_list_subscribers():
	fields = list(Subscriber.objects.values())
	subscribers = {'fields':fields}
	return JsonResponse(subscribers)

def get_subscribers(request):
	return make_list_subscribers()

def create_subscriber(request):
	if request.method == 'POST':
		name = request.POST['name']
		email = request.POST['email']
		password = request.POST['password']
		Subscriber.objects.create(name=name, email=email, password=password)
	return make_list_subscribers()

def view_registrationpage(request):
	form = Subscribe_Form()
	return render(request, 'Registrationpage.html', {'form':form})

booksthismonth/templates/Booksthismonth.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

		<div class="container-fluid">

			<div class="row">
				<div class="col-md-2">
					<h3>Search books:</h3>
				</div>				
				<div class="col-md-4">
					<div class="row">
						<div class="col-md-8 form-group">
							<input type="text" class="form-control" id="usr" name="username">
						</div>
						<div class="col-md-4">
							<button onclick="search()" class="btn btn-primary">Search</button>
						</div>									
					</div>
				</div>
				<div class="col-md-4">
					<h3 id="favorite">Favorite(s): 0</h3>
				</div>
			</div>			

			<div class="row">
				<table class="table table-responsive">
					<thead>
						<tr>
							<th>No.</th>
							<th>Title</th>
							<th>Author</th>
							<th>Published Date</th>
							<th>Description</th>
							<th>Cover</th>
							<th>Add to favorite</th>
						</tr>
					</thead>
					<tbody>						
					</tbody>
				</table>
			</div>

		</div>

{% endblock %}

feedbackpage/templates/Feedbackpage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

		<div class="container-fluid">

			<div class="text-center" id="feedback-rectangle">
				<h2>
					“We all need people who will give us feedback. That’s how we improve.” -Bill Gates
				</h2>
			</div>

			<div class="content text-center">
				<h2>Feedback form</h2>
				<form method="POST" class="row post-form">
					{% csrf_token %}
					<div>
						<table>
							{{ form.as_table }}
						</table>					
					</div>						
					<div>
						<button type="submit" class="save btn btn-success">Submit</button>
					</div>					
				</form>
			</div>

		</div>

{% endblock %}

loginpage/templates/Loginpage.html
{% extends "base.html" %}
{% block content %}

  <h2>Login</h2>
  <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>

{% endblock %}

profilepage/templates/Profilepage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

			<div class="row rectangle" id="rectangle1">
				<div class="col-md-5 text-center">
					<img class="img-responsive img-profile" src="{% static 'foto profil.jpg' %}">
				</div>
				<div class="col-md-7">
					<h3 class="text-name">Ardian Ghifari</h3>
					<h1 class="text-desc">A passionate student</h1>
					<h4 class="text-desc">Not an ordinary outlier</h4>
					<h4 class="text-desc">Love to learn and learn to love everything related to data</h4>
				</div>	
			</div>

			<div class="rectangle small-rectangle" id="about-div">
				<div class="text-center" id="about-title">
					<h2 class="text-title">About</h2>
				</div>	
				<div class="col-md-8 text-paragraph1" id="about-paragraph">
					<h3>
						I am a student of Computer Science major of Universitas Indonesia. I am not an expert yet in data science, I am still learning everything related to data. I am very interested in seeking certification, internship, and project.
					</h3>
				</div>							
			</div>
			
			<div class="rectangle big-rectangle" id="experience-div">
				<div class="text-center">
					<h2 class="text-title" id="experience-title">Experience</h2>	
				</div>
				<div class="text-center text-paragraph2" id="experience-paragraph">
					<h3>
						2014 - 2015 Staff of OSIS SMAN 5 Bekasi <br>
						2015 Staff of Equipment FiveCup SMAN 5 Bekasi <br>
						2015 Secretary of Idul Adha in SMAN 5 Bekasi <br>
						2015 - 2016 Secretary of ICT SMAN 5 Bekasi <br>
						2016 PIC of Short Movie Competition in STC SMAN 5 Bekasi <br>
						2018 Staff of FUKI Fasilkom UI <br>
						2018 Staff of Data Science Academy CompFest X
					</h3>
				</div>	
			</div>

			<div class="rectangle small-rectangle" id="skill-div">
				<div class="text-center" id="skill-title">
					<h2 class="text-title">Skill</h2>
				</div>	
				<div class="col-md-8 text-paragraph1" id="skill-paragraph">
					<h3>
						English language <br>
						Python <br>
						Java <br>
						Cmap <br>
						Microsoft Excel
					</h3>
				</div>							
			</div>

			<div class="rectangle big-rectangle" id="education-div">
				<div class="text-center">
					<h2 class="text-title" id="education-title">Education</h2>	
				</div>
				<div class="text-center text-paragraph2" id="education-paragraph">
					<h3>
						2014 - 2017 SMAN 5 Bekasi <br>
						2014 - 2017 LBPP LIA (English Course) <br>
						2017 - Universitas Indonesia
					</h3>
				</div>	
			</div>

{% endblock %}

registrationpage/templates/Registrationpage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

		<div class="container-fluid">

			<div class="content text-center">
				<h2>Register to subscribe to my portfolio</h2>
				<form method="POST" class="row post-form">
					{% csrf_token %}
					<div>
						<table>
							{{ form.as_table }}
						</table>					
					</div>
					<div>
						<p id="email-alert"></p>					
					</div>					
					<div>
						<button type="submit" class="save btn btn-success" id="subscribe-button">Submit</button>
					</div>					
				</form>
			</div>

		</div>

{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8"> 
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Ardian Ghifari - A passionate student</title>
		<link rel="stylesheet" type="text/css" href="{% static 'Profilepage.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'Feedbackpage.css' %}">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
		<script src="{% static 'Profilepage.js' %}"></script>
		<script src="{% static 'Registrationpage.js' %}"></script>
		<script src="{% static 'Booksthismonth.js' %}"></script>
	<body>

		<div class="loader text-center">
			<h2>Orang sabar disayang mantan</h2>
			<div class="spinner"></div>
		</div>

		<div class="container-fluid" id="main">

			<nav class="row navbar navbar-expand-sm bg-success navbar-dark" id="header">
			  <ul class="navbar-nav">
			    <li class="nav-item active">
			      <a class="nav-link" href="{% url 'profilepage' %}">Home</a>
			    </li>
			  </ul>
			    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
			    	<span class="navbar-toggler-icon"></span>
			    </button>
			    <div class="collapse navbar-collapse" id="collapsibleNavbar">
				    <ul class="navbar-nav">
				    	<li><a class="nav-link" href="#" id="change-theme">Kami cinta fasilkom</a></li>
				    	<li><a class="nav-link" href="{% url 'booksthismonth' %}">Search books</a></li>
				    	<li><a class="nav-link" href="{% url 'registrationpage' %}">Subscribe</a></li>
				    	{% if user.is_authenticated %}
				    	<li><a class="nav-link">Hello, {{ user.username }}</a></li>
						{% endif %}				    		   	
				    </ul>
				    <ul class="navbar-nav ml-auto">
				    	<li>
				    	{% if user.is_authenticated %}
			            	<a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
						{% else %}							
				    		<a class="nav-link" href="{% url 'login:loginpage' %}">Login</a>
						{% endif %}
						</li>	
				    </ul>
				  </div>  
			</nav>

			{% block content %}
			{% endblock content %}
			
			<div id="footer">
				<div class="row text-center">
					<h4 class="text-footer">Contact me</h4>
				</div>		
				<div class="row">
					<div class="col-sm-4">									
		                <div class="row text-center">
		                    <h5 class="text-footer">
		                    	<span class="fas fa-phone"></span>+62 858 1191 6028
		                    </h5>
		                </div>
		                <div class="row text-center">
		                    <h5 class="text-footer">
		                    	<span class="fas fa-at"></span>ardianghi@gmail.com
		                    </h5>
		                </div>
		            </div>
		            <div class="col-sm-4">
		                <div class="row text-center">
		                	<h5 class="text-footer">
		                		<span class="fab fa-line"></span>@ardianghifari
		                	</h5>
		                </div>
		                <div class="row text-center">
		                	<h5 class="text-footer">
		                		<span class="fab fa-instagram"></span>@ardianghifari
		                	</h5>
		                </div>
					</div>				
					<div class="col-sm-4">
						<h5><a href="{% url 'feedbackpage' %}" class="text-footer">
						Feedback
						</a></h5>
						<h5 class="text-footer" id="backtotop">Back to Top</h5>
					</div>
				</div>	
		</div>

		</div>
		
	</body>

</html>